<?php
//include("form.php");
// include("config/connection.php");

$apikey = "rzp_test_Pl81xvWKLN0yIB";

$Total_Price = $_GET['price'];


?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>

<form action="pending.php?price=<?php echo $Total_Price; ?>" method="get">
   <script
      src="https://checkout.razorpay.com/v1/checkout.js"
      data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
      data-amount=" <?php echo $_GET['price'] * 100  ?> " // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
      data-currency="INR" // You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
      data_Order_id=" " // Replace with the order_id generated by you in the backend.
      data-header="<h1> Hello harsh..!</h1>"
      data-buttontext="Pay with Razorpay"
      data-name="The Real-Travel.com"
      data-description=" This is the demo payment..!"
      data-image="https://traidev.com/img/web-design-development.png"
      data-prefill.name="The Real-Travel.com"
      data-prefill.email="<?php echo $_POST['emails']; ?>"
      data-theme.color="blue"></script>
   <!-- <input type="hidden" custom="Hidden Element" name="hidden"/> -->
</form>
<style>
   .razorpay-payment-button {
      display: none;
   }
</style>

<script type="text/javascript">
   $(document).ready(function() {

      $('.razorpay-payment-button').click();

   })
</script>
 
<?php  
?>